sudo: required
services:
  - docker

before_install:
  - docker build -t telman/test-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true telman/test-react npm run test

after_success:
  - docker build -t 870414/multi-client ./client
  - docker build -t 870414/multi-nginx ./nginx
  - docker build -t 870414/multi-server ./server
  - docker build -t 870414/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push 870414/multi-client
  - docker push 870414/multi-nginx
  - docker push 870414/multi-server
  - docker push 870414/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: "docker-multi"
  env: "DockerMulti-env"
  bucket_name: "elasticbeanstalk-eu-central-1-677022027905"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY